### ISSUE TITLE
couple of issues here | main problem rn:  expected str, bytes or os.PathLike object, not GeneralizedRCNN

### ISSUE THREAD

**Issue by dragoscosma** [segments-ai/fast-labeling-workflow#1]
line 64 under utils had to be changed to:  cfg.merge_from_file(model_zoo.get("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))

I'm following the steps mentioned in your article: https://segments.ai/blog/speed-up-image-segmentation-with-model-assisted-labeling
currently getting the following error at line: model = train_model(dataset)

Metadata(evaluator_type='coco', image_root='segments\\Dragos_Mycars\\v0.1', json_file='041ae42f-25aa-434e-a303-1afbcfa3ce90_coco.json', name='my_dataset', thing_classes=['car'])
Config 'c:\users\<>\detectron2\detectron2\model_zoo\configs\COCO-InstanceSegmentation\mask_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "c:\Users\<>\2-1.py", line 28, in <module>
    model = train_model(dataset)
  File "C:/Users/<>/fast-labeling-workflow\utils.py", line 64, in train_model
    cfg.merge_from_file(model_zoo.get("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
  File "c:\users\<>\detectron2\detectron2\config\config.py", line 23, in merge_from_file
    loaded_cfg = _CfgNode.load_yaml_with_base(cfg_filename, allow_unsafe=allow_unsafe)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fvcore\common\config.py", line 49, in load_yaml_with_base
    with PathManager.open(filename, "r") as f:
  File "C:\ProgramData\Anaconda3\lib\site-packages\fvcore\common\file_io.py", line 647, in open
    return self.__get_path_handler(path)._open(  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\fvcore\common\file_io.py", line 622, in __get_path_handler
    path = os.fspath(path)  # pyre-ignore
TypeError: expected str, bytes or os.PathLike object, not GeneralizedRCNN

running this from W10
CUDA version: 10.2
Anaconda
Python 3.8.3
tried running under different conda environments (tried base and new env)
reinstalled fvcore

----------
On a separate note can you explain what is needed at this line: 
Get a list of image URLs
image_urls = get_image_urls('tomatoes')

I've tried comma delimited URLS, tried OneDrive4B accessible URL containing images, tried OneDrive4B accessible URL to a JSON file containing image URLS. tried local json file, tried txt file containing comma delimited URLs.

---------
Also utils line: 69. model_zoo has no such function get_checkpoint_url

thank you

**Comment by dbbert** [comment]
Have you tried running the Colab notebook? https://colab.research.google.com/github/segments-ai/predictive-labeling-workflow/blob/master/demo.ipynb

If you don't encounter those issues there, they are most likely caused by your environment and/or dependencies. The code has not been tested on Windows.
