### ISSUE TITLE
Detectron 2 not Windows compatible

### ISSUE THREAD

**Issue by CaseGuide** [segments-ai/fast-labeling-workflow#4]
Hey, I want to try SegmentsAI via the demo and even uploaded and labeled some sample files but can't move past `from utils import get_image_urls` because detectron2 isn't compatible with Windows it seems. Or, at a minimum, doesn't offer prebuilt binaries. This is too high of a barrier of entry just to test your product. If you 

`pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.8/index.html` fails on Win10 with error

```
ERROR: Could not find a version that satisfies the requirement detectron2 (from versions: none)
ERROR: No matching distribution found for detectron2
```

**Comment by dbbert** [comment]
Yes, detectron2 requires a Linux setup unfortunately. Although it [does seem possible](https://github.com/facebookresearch/detectron2/issues/9) to install it on Windows as well. 

The easiest way to try the tutorial yourself is through the [Google Colab](https://colab.research.google.com/github/segments-ai/fast-labeling-workflow/blob/master/demo.ipynb).
